#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Script arguments are passed to oe-init-build-env and we don't want that.
EXEC_ARGS=("${@}")
shift "${#}"

set +eu
. sources/poky/oe-init-build-env
set -eu

cp ../local.conf conf/

# shellcheck disable=SC2048
exec ${EXEC_ARGS[*]}
